spring:
  application:
    name: elearning
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/elearning
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: 127.0.0.1
    port: 1025
    username: noreply@doubi.fr
    properties:
      smtp:
        auth: false
        starttls:
          enable: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope:
              - email
              - profile

logging:
  level:
    org.springframework.security: TRACE

application:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600000
      refresh-token:
        expiration: 2592000000
